backend:
  name: git-gateway
  branch: main

media_folder: "notes"
public_folder: "/notes"

collections:
  - name: "materials"
    label: "Study Materials"

    files:
      - label: "Materials Data"
        name: "materials_data"
        file: "materials.json"

        fields:
          - label: "Materials"
            name: "materials"
            widget: "list"

            fields:
              - { label: "Title", name: "title", widget: "string" }

              - { label: "Description", name: "description", widget: "text" }

              - { label: "PDF", name: "pdf", widget: "file" }